# Generated by Django 3.2 on 2023-10-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20231006_0347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='line',
            table='line_tbl',
        ),
        migrations.AlterModelTable(
            name='script',
            table='script_tbl',
        ),
    ]
