version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - node_modules:/src/node_modules
      # ↑ 次回起動後にコメントアウトを解除
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    links:
      - api-server

  api-server:
    # Dockerfileの場所
    build: 
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/workspace
    tty: true
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/

volumes:
  node_modules:
