version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/src
    working_dir: "/src"
    ports:
      - "3000:3000"
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
    depends_on:
    - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/

volumes:
  node_modules:
