name: Build and Deploy to S3

on:
  push:
    branches:
      - vuetify-practice2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build Nuxt.js
        run: yarn generate:dev
      
      - name: List directory contents
        run: ls -la
        
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: aws s3 cp --recursive --region ap-northeast-1 ./dist s3://portfolio-tadaki --acl public-read
