name: Build and Deploy to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check directory
        run: |
          echo $GITHUB_WORKSPACE
          ls -la

      - name: Install dependencies
        run: npm install
      
      # Assuming there's an equivalent script in package.json for 'generate:dev'
      - name: Build Nuxt.js
        run: npm run generate
      
      - name: List directory contents
        run: ls -la
        
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 cp --recursive --region ap-northeast-1 ./dist s3://portfolio-tadaki
          echo "AWS CF reset"
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} --paths "/*"
        
